name: New issue

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues:
    types: [opened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Afficher qu'une issue est ouverte sur le repo
        run: echo "Une issue est ouverte !"
